2025-04-21 09:48:55.974431 - Primary server down! Initiating failover...
2025-04-21 09:49:00.080184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1907AA420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:05.086077 - Primary server down! Initiating failover...
2025-04-21 09:49:09.186184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:14.196321 - Primary server down! Initiating failover...
2025-04-21 09:49:18.278341 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:23.286987 - Primary server down! Initiating failover...
2025-04-21 09:49:27.361191 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:32.370625 - Primary server down! Initiating failover...
2025-04-21 09:49:36.464439 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:41.474014 - Primary server down! Initiating failover...
2025-04-21 09:49:45.554772 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4FE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:50.566231 - Primary server down! Initiating failover...
2025-04-21 09:49:54.673839 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E806B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:59.684251 - Primary server down! Initiating failover...
2025-04-21 09:50:03.772106 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1932B7D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
