2025-04-21 09:48:55.974431 - Primary server down! Initiating failover...
2025-04-21 09:49:00.080184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1907AA420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:05.086077 - Primary server down! Initiating failover...
2025-04-21 09:49:09.186184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:14.196321 - Primary server down! Initiating failover...
2025-04-21 09:49:18.278341 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:23.286987 - Primary server down! Initiating failover...
2025-04-21 09:49:27.361191 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:32.370625 - Primary server down! Initiating failover...
2025-04-21 09:49:36.464439 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:41.474014 - Primary server down! Initiating failover...
2025-04-21 09:49:45.554772 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4FE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:50.566231 - Primary server down! Initiating failover...
2025-04-21 09:49:54.673839 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E806B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:59.684251 - Primary server down! Initiating failover...
2025-04-21 09:50:03.772106 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1932B7D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:28.137094 - Primary server down! Initiating failover...
2025-04-22 08:26:32.261129 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:37.272782 - Primary server down! Initiating failover...
2025-04-22 08:26:41.403676 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:46.418164 - Primary server down! Initiating failover...
2025-04-22 08:26:50.527435 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:55.540960 - Primary server down! Initiating failover...
2025-04-22 08:26:59.641942 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8656A8200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:04.652351 - Primary server down! Initiating failover...
2025-04-22 08:27:08.791692 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B05C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:13.796568 - Primary server down! Initiating failover...
2025-04-22 08:27:17.906849 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:22.916250 - Primary server down! Initiating failover...
2025-04-22 08:27:27.045972 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B1520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:32.057438 - Primary server down! Initiating failover...
2025-04-22 08:27:36.175937 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C864D25D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:41.189172 - Primary server down! Initiating failover...
2025-04-22 08:27:45.300037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:50.316991 - Primary server down! Initiating failover...
2025-04-22 08:27:54.424037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B11F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:59.432200 - Primary server down! Initiating failover...
2025-04-22 08:28:03.535293 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:08.540544 - Primary server down! Initiating failover...
2025-04-22 08:28:12.666074 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:17.674748 - Primary server down! Initiating failover...
2025-04-22 08:28:21.772275 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:26.783925 - Primary server down! Initiating failover...
2025-04-22 08:28:30.879967 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2E40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:35.892430 - Primary server down! Initiating failover...
2025-04-22 08:28:40.009438 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:45.016022 - Primary server down! Initiating failover...
2025-04-22 08:28:49.140819 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B24E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:54.153837 - Primary server down! Initiating failover...
2025-04-22 08:28:58.253703 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:03.259330 - Primary server down! Initiating failover...
2025-04-22 08:29:07.358527 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:12.370508 - Primary server down! Initiating failover...
2025-04-22 08:29:16.505378 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B12E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:21.519632 - Primary server down! Initiating failover...
2025-04-22 08:29:25.634458 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B1B20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:30.640325 - Primary server down! Initiating failover...
2025-04-22 08:29:34.729477 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:39.740989 - Primary server down! Initiating failover...
2025-04-22 08:29:43.868730 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:48.883130 - Primary server down! Initiating failover...
2025-04-22 08:29:53.013198 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B04D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:58.021100 - Primary server down! Initiating failover...
2025-04-22 08:30:02.132863 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:07.137336 - Primary server down! Initiating failover...
2025-04-22 08:30:11.252116 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:16.264930 - Primary server down! Initiating failover...
2025-04-22 08:30:20.400452 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:25.409077 - Primary server down! Initiating failover...
2025-04-22 08:30:29.510261 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783830>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:34.516393 - Primary server down! Initiating failover...
2025-04-22 08:30:38.621450 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:43.633531 - Primary server down! Initiating failover...
2025-04-22 08:30:47.752091 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:52.757667 - Primary server down! Initiating failover...
2025-04-22 08:30:56.842759 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:01.850707 - Primary server down! Initiating failover...
2025-04-22 08:31:05.964367 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:10.977721 - Primary server down! Initiating failover...
2025-04-22 08:31:15.090407 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B3710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:20.104328 - Primary server down! Initiating failover...
2025-04-22 08:31:24.223037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:29.234241 - Primary server down! Initiating failover...
2025-04-22 08:31:33.339701 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:38.348958 - Primary server down! Initiating failover...
2025-04-22 08:31:42.441581 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:47.455495 - Primary server down! Initiating failover...
2025-04-22 08:31:51.565960 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:56.574810 - Primary server down! Initiating failover...
2025-04-22 08:32:00.657521 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B25D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:33:44.323178 - Primary server down! Initiating failover...
2025-04-22 09:33:48.408854 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518EC9DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:33:53.421641 - Primary server down! Initiating failover...
2025-04-22 09:33:57.518167 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:02.526222 - Primary server down! Initiating failover...
2025-04-22 09:34:06.638167 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518D489E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:11.644036 - Primary server down! Initiating failover...
2025-04-22 09:34:15.763276 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:20.771998 - Primary server down! Initiating failover...
2025-04-22 09:34:24.872433 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:29.884007 - Primary server down! Initiating failover...
2025-04-22 09:34:33.986550 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E7E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:38.991975 - Primary server down! Initiating failover...
2025-04-22 09:34:43.100183 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EFC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:48.108898 - Primary server down! Initiating failover...
2025-04-22 09:34:52.200705 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518AF6300>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:34:57.212100 - Primary server down! Initiating failover...
2025-04-22 09:35:01.300763 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8ED20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:06.308877 - Primary server down! Initiating failover...
2025-04-22 09:35:10.413617 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E7B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:15.420006 - Primary server down! Initiating failover...
2025-04-22 09:35:19.524230 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DFA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:24.531071 - Primary server down! Initiating failover...
2025-04-22 09:35:28.647281 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DBB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:33.653371 - Primary server down! Initiating failover...
2025-04-22 09:35:37.761998 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FFB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:42.769702 - Primary server down! Initiating failover...
2025-04-22 09:35:46.867483 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F15D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:35:51.880419 - Primary server down! Initiating failover...
2025-04-22 09:35:56.000289 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FC20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:01.013128 - Primary server down! Initiating failover...
2025-04-22 09:36:05.132517 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:10.148548 - Primary server down! Initiating failover...
2025-04-22 09:36:14.261090 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:19.267486 - Primary server down! Initiating failover...
2025-04-22 09:36:23.348404 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:28.358462 - Primary server down! Initiating failover...
2025-04-22 09:36:32.451306 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8F1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:37.467151 - Primary server down! Initiating failover...
2025-04-22 09:36:41.572024 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519308920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:46.581518 - Primary server down! Initiating failover...
2025-04-22 09:36:50.664208 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:36:55.680330 - Primary server down! Initiating failover...
2025-04-22 09:36:59.762759 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:04.768900 - Primary server down! Initiating failover...
2025-04-22 09:37:08.853055 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DDC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:13.865791 - Primary server down! Initiating failover...
2025-04-22 09:37:17.956374 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8CE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:22.967629 - Primary server down! Initiating failover...
2025-04-22 09:37:27.061692 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:32.074107 - Primary server down! Initiating failover...
2025-04-22 09:37:36.171163 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519308800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:41.183573 - Primary server down! Initiating failover...
2025-04-22 09:37:45.276394 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FF80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:50.290095 - Primary server down! Initiating failover...
2025-04-22 09:37:54.397991 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DAC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:37:59.413570 - Primary server down! Initiating failover...
2025-04-22 09:38:03.524433 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:05.151334 - Primary server down! Initiating failover...
2025-04-22 09:38:08.536465 - Primary server down! Initiating failover...
2025-04-22 09:38:09.276574 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB6F5A420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:12.657901 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E9F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:14.284433 - Primary server down! Initiating failover...
2025-04-22 09:38:17.671075 - Primary server down! Initiating failover...
2025-04-22 09:38:18.388759 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DAF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:21.764599 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8F0B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:23.396035 - Primary server down! Initiating failover...
2025-04-22 09:38:26.779237 - Primary server down! Initiating failover...
2025-04-22 09:38:27.502265 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:30.900203 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519308890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:32.508032 - Primary server down! Initiating failover...
2025-04-22 09:38:35.906004 - Primary server down! Initiating failover...
2025-04-22 09:38:36.601525 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:39.996627 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:41.609304 - Primary server down! Initiating failover...
2025-04-22 09:38:45.004808 - Primary server down! Initiating failover...
2025-04-22 09:38:45.726237 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:49.110446 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DF70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:50.736430 - Primary server down! Initiating failover...
2025-04-22 09:38:54.117980 - Primary server down! Initiating failover...
2025-04-22 09:38:54.871695 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E960>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:58.220225 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DA30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:38:59.877772 - Primary server down! Initiating failover...
2025-04-22 09:39:03.233668 - Primary server down! Initiating failover...
2025-04-22 09:39:03.964398 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:07.345414 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8F9E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:08.969667 - Primary server down! Initiating failover...
2025-04-22 09:39:12.352208 - Primary server down! Initiating failover...
2025-04-22 09:39:13.105596 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB6DB5F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:16.431967 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025517520680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:18.113811 - Primary server down! Initiating failover...
2025-04-22 09:39:21.444501 - Primary server down! Initiating failover...
2025-04-22 09:39:22.227686 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:25.559380 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:27.241435 - Primary server down! Initiating failover...
2025-04-22 09:39:30.569647 - Primary server down! Initiating failover...
2025-04-22 09:39:31.344961 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:34.662264 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FBF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:36.356393 - Primary server down! Initiating failover...
2025-04-22 09:39:39.673384 - Primary server down! Initiating failover...
2025-04-22 09:39:40.462662 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701CE00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:43.752941 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:45.470945 - Primary server down! Initiating failover...
2025-04-22 09:39:48.758996 - Primary server down! Initiating failover...
2025-04-22 09:39:49.590340 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:52.877841 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DDF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:39:54.601869 - Primary server down! Initiating failover...
2025-04-22 09:39:57.890579 - Primary server down! Initiating failover...
2025-04-22 09:39:58.726596 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7398170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:02.007703 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EEA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:03.732627 - Primary server down! Initiating failover...
2025-04-22 09:40:07.022661 - Primary server down! Initiating failover...
2025-04-22 09:40:07.837149 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB6D83F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:11.120783 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518E260C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:12.849761 - Primary server down! Initiating failover...
2025-04-22 09:40:16.127463 - Primary server down! Initiating failover...
2025-04-22 09:40:16.943410 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:20.206432 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309A60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:21.948722 - Primary server down! Initiating failover...
2025-04-22 09:40:25.216589 - Primary server down! Initiating failover...
2025-04-22 09:40:26.035755 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E300>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:29.324283 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:31.051545 - Primary server down! Initiating failover...
2025-04-22 09:40:34.334541 - Primary server down! Initiating failover...
2025-04-22 09:40:35.165608 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:38.403880 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E360>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:40.179699 - Primary server down! Initiating failover...
2025-04-22 09:40:43.411153 - Primary server down! Initiating failover...
2025-04-22 09:40:44.316469 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701EF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:47.523790 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:49.328070 - Primary server down! Initiating failover...
2025-04-22 09:40:52.536694 - Primary server down! Initiating failover...
2025-04-22 09:40:53.440106 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:56.632879 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DB80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:40:58.452015 - Primary server down! Initiating failover...
2025-04-22 09:41:01.644446 - Primary server down! Initiating failover...
2025-04-22 09:41:02.534550 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7398AA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:05.772889 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518EF1400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:07.547961 - Primary server down! Initiating failover...
2025-04-22 09:41:10.785819 - Primary server down! Initiating failover...
2025-04-22 09:41:11.642506 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:14.900276 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A2A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:16.655569 - Primary server down! Initiating failover...
2025-04-22 09:41:19.911559 - Primary server down! Initiating failover...
2025-04-22 09:41:20.753053 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:24.026347 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D8E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:25.767304 - Primary server down! Initiating failover...
2025-04-22 09:41:29.038081 - Primary server down! Initiating failover...
2025-04-22 09:41:29.849954 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E0C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:33.152142 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E300>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:34.860064 - Primary server down! Initiating failover...
2025-04-22 09:41:38.163772 - Primary server down! Initiating failover...
2025-04-22 09:41:38.976574 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DCA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:42.283723 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:43.982023 - Primary server down! Initiating failover...
2025-04-22 09:41:47.293990 - Primary server down! Initiating failover...
2025-04-22 09:41:48.106648 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F9E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:51.400677 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EAE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:41:53.118782 - Primary server down! Initiating failover...
2025-04-22 09:41:56.414598 - Primary server down! Initiating failover...
2025-04-22 09:41:57.240202 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB73988F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:00.520206 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518DD97F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:02.252543 - Primary server down! Initiating failover...
2025-04-22 09:42:05.528336 - Primary server down! Initiating failover...
2025-04-22 09:42:06.348851 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DBB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:09.591455 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930AAB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:11.360307 - Primary server down! Initiating failover...
2025-04-22 09:42:14.599082 - Primary server down! Initiating failover...
2025-04-22 09:42:15.459672 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DEB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:18.706531 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:20.474323 - Primary server down! Initiating failover...
2025-04-22 09:42:23.712130 - Primary server down! Initiating failover...
2025-04-22 09:42:24.559509 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701EE40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:27.821771 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:29.563918 - Primary server down! Initiating failover...
2025-04-22 09:42:32.829614 - Primary server down! Initiating failover...
2025-04-22 09:42:33.661161 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:36.958023 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:38.673199 - Primary server down! Initiating failover...
2025-04-22 09:42:41.972046 - Primary server down! Initiating failover...
2025-04-22 09:42:42.761284 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F1A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:46.065632 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8D4F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:47.768783 - Primary server down! Initiating failover...
2025-04-22 09:42:51.076245 - Primary server down! Initiating failover...
2025-04-22 09:42:51.875710 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7398A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:55.183134 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025517520680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:42:56.882089 - Primary server down! Initiating failover...
2025-04-22 09:43:00.193029 - Primary server down! Initiating failover...
2025-04-22 09:43:00.963199 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:04.305925 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:05.979301 - Primary server down! Initiating failover...
2025-04-22 09:43:09.317944 - Primary server down! Initiating failover...
2025-04-22 09:43:10.097167 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:10.352391 - Primary server down! Initiating failover...
2025-04-22 09:43:13.429368 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FF80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:14.467513 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002643D11C920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:15.103542 - Primary server down! Initiating failover...
2025-04-22 09:43:18.440099 - Primary server down! Initiating failover...
2025-04-22 09:43:19.213432 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DC10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:19.475875 - Primary server down! Initiating failover...
2025-04-22 09:43:22.521487 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E0C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:23.558145 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002643D11CFE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:24.224350 - Primary server down! Initiating failover...
2025-04-22 09:43:27.532140 - Primary server down! Initiating failover...
2025-04-22 09:43:28.334323 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FD40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:28.565641 - Primary server down! Initiating failover...
2025-04-22 09:43:31.631536 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:33.346533 - Primary server down! Initiating failover...
2025-04-22 09:43:36.639961 - Primary server down! Initiating failover...
2025-04-22 09:43:37.450553 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB639A840>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:40.733953 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:42.463396 - Primary server down! Initiating failover...
2025-04-22 09:43:45.750876 - Primary server down! Initiating failover...
2025-04-22 09:43:46.594030 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399340>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:49.852030 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B0E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:51.606620 - Primary server down! Initiating failover...
2025-04-22 09:43:54.859752 - Primary server down! Initiating failover...
2025-04-22 09:43:55.730061 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FBF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:43:58.963896 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930BC20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:00.742947 - Primary server down! Initiating failover...
2025-04-22 09:44:03.978089 - Primary server down! Initiating failover...
2025-04-22 09:44:04.838869 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D8B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:08.081228 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:09.853556 - Primary server down! Initiating failover...
2025-04-22 09:44:13.095788 - Primary server down! Initiating failover...
2025-04-22 09:44:13.976403 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E360>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:17.217521 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E7B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:18.988684 - Primary server down! Initiating failover...
2025-04-22 09:44:22.225710 - Primary server down! Initiating failover...
2025-04-22 09:44:23.113662 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:26.330924 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E180>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:28.129312 - Primary server down! Initiating failover...
2025-04-22 09:44:31.347965 - Primary server down! Initiating failover...
2025-04-22 09:44:32.229278 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB55B0680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:35.453751 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:37.236302 - Primary server down! Initiating failover...
2025-04-22 09:44:40.460491 - Primary server down! Initiating failover...
2025-04-22 09:44:41.335416 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:44.556493 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B0E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:46.348287 - Primary server down! Initiating failover...
2025-04-22 09:44:49.568620 - Primary server down! Initiating failover...
2025-04-22 09:44:50.477240 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:53.654633 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519334500>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:44:55.482748 - Primary server down! Initiating failover...
2025-04-22 09:44:58.665636 - Primary server down! Initiating failover...
2025-04-22 09:44:59.585764 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E000>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:02.755351 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519308EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:04.591216 - Primary server down! Initiating failover...
2025-04-22 09:45:07.761656 - Primary server down! Initiating failover...
2025-04-22 09:45:08.688562 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E2A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:11.853161 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930AF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:13.700448 - Primary server down! Initiating failover...
2025-04-22 09:45:16.857759 - Primary server down! Initiating failover...
2025-04-22 09:45:17.819851 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:20.963289 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A3F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:22.827572 - Primary server down! Initiating failover...
2025-04-22 09:45:25.973851 - Primary server down! Initiating failover...
2025-04-22 09:45:26.940906 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB6386300>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:30.085577 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A2A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:31.953963 - Primary server down! Initiating failover...
2025-04-22 09:45:35.097982 - Primary server down! Initiating failover...
2025-04-22 09:45:36.056554 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739A480>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:39.212933 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255193099D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:41.063802 - Primary server down! Initiating failover...
2025-04-22 09:45:44.221112 - Primary server down! Initiating failover...
2025-04-22 09:45:45.187182 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FB60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:48.305771 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519308E60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:50.197657 - Primary server down! Initiating failover...
2025-04-22 09:45:53.311593 - Primary server down! Initiating failover...
2025-04-22 09:45:54.330578 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:57.417061 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309E20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:45:59.343835 - Primary server down! Initiating failover...
2025-04-22 09:46:02.424284 - Primary server down! Initiating failover...
2025-04-22 09:46:03.430254 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E0F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:06.510476 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A660>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:08.442408 - Primary server down! Initiating failover...
2025-04-22 09:46:11.517993 - Primary server down! Initiating failover...
2025-04-22 09:46:12.563472 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E6F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:15.616190 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930AFF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:17.568061 - Primary server down! Initiating failover...
2025-04-22 09:46:20.620805 - Primary server down! Initiating failover...
2025-04-22 09:46:21.638020 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB5CB9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:24.757948 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B8C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:26.648374 - Primary server down! Initiating failover...
2025-04-22 09:46:29.762749 - Primary server down! Initiating failover...
2025-04-22 09:46:30.768984 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739ACC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:33.871810 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:35.774563 - Primary server down! Initiating failover...
2025-04-22 09:46:38.878600 - Primary server down! Initiating failover...
2025-04-22 09:46:39.894597 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:42.990164 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255193084D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:44.910297 - Primary server down! Initiating failover...
2025-04-22 09:46:48.008041 - Primary server down! Initiating failover...
2025-04-22 09:46:49.012383 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:52.117944 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A7E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:46:54.023933 - Primary server down! Initiating failover...
2025-04-22 09:46:57.129361 - Primary server down! Initiating failover...
2025-04-22 09:46:58.134084 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E0C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:01.244088 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B1A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:03.148280 - Primary server down! Initiating failover...
2025-04-22 09:47:06.259133 - Primary server down! Initiating failover...
2025-04-22 09:47:07.235540 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DCA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:10.356716 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:12.249060 - Primary server down! Initiating failover...
2025-04-22 09:47:15.369306 - Primary server down! Initiating failover...
2025-04-22 09:47:16.371442 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB6E6B020>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:19.475557 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:21.385759 - Primary server down! Initiating failover...
2025-04-22 09:47:24.488989 - Primary server down! Initiating failover...
2025-04-22 09:47:25.503037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:26.204687 - Primary server down! Initiating failover...
2025-04-22 09:47:28.604755 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309D00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:30.314234 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024CC3F1C8C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:30.514322 - Primary server down! Initiating failover...
2025-04-22 09:47:33.616297 - Primary server down! Initiating failover...
2025-04-22 09:47:34.620376 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FB30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:35.326686 - Primary server down! Initiating failover...
2025-04-22 09:47:37.713275 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F14EC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:39.629266 - Primary server down! Initiating failover...
2025-04-22 09:47:42.754558 - Primary server down! Initiating failover...
2025-04-22 09:47:43.747012 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701D7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:46.882228 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:48.756392 - Primary server down! Initiating failover...
2025-04-22 09:47:51.892235 - Primary server down! Initiating failover...
2025-04-22 09:47:52.858371 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:56.007584 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A6C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:47:57.864510 - Primary server down! Initiating failover...
2025-04-22 09:48:01.020209 - Primary server down! Initiating failover...
2025-04-22 09:48:01.976559 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E3C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:05.158873 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:06.989310 - Primary server down! Initiating failover...
2025-04-22 09:48:10.028099 - Primary server down! Initiating failover...
2025-04-22 09:48:10.174368 - Primary server down! Initiating failover...
2025-04-22 09:48:11.118446 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B2C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:14.275507 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:16.130045 - Primary server down! Initiating failover...
2025-04-22 09:48:19.288424 - Primary server down! Initiating failover...
2025-04-22 09:48:20.247444 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BE30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:23.380917 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518DD97F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:25.256029 - Primary server down! Initiating failover...
2025-04-22 09:48:28.389256 - Primary server down! Initiating failover...
2025-04-22 09:48:29.347852 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701EC00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:32.488573 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8FA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:34.354688 - Primary server down! Initiating failover...
2025-04-22 09:48:37.495543 - Primary server down! Initiating failover...
2025-04-22 09:48:38.459264 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701E240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:41.607060 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B6E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:43.467281 - Primary server down! Initiating failover...
2025-04-22 09:48:46.612415 - Primary server down! Initiating failover...
2025-04-22 09:48:47.583497 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FF20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:50.701827 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B170>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:52.590239 - Primary server down! Initiating failover...
2025-04-22 09:48:55.710196 - Primary server down! Initiating failover...
2025-04-22 09:48:56.705610 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701F980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:48:59.811511 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:01.715643 - Primary server down! Initiating failover...
2025-04-22 09:49:04.822555 - Primary server down! Initiating failover...
2025-04-22 09:49:05.804644 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B6B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:08.957626 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309370>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:10.808633 - Primary server down! Initiating failover...
2025-04-22 09:49:13.971857 - Primary server down! Initiating failover...
2025-04-22 09:49:14.926111 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB73C46E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:18.073993 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551593C110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:19.937290 - Primary server down! Initiating failover...
2025-04-22 09:49:23.087515 - Primary server down! Initiating failover...
2025-04-22 09:49:24.031707 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:27.181511 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E0F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:29.039972 - Primary server down! Initiating failover...
2025-04-22 09:49:32.191656 - Primary server down! Initiating failover...
2025-04-22 09:49:33.144804 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:36.291541 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:38.151630 - Primary server down! Initiating failover...
2025-04-22 09:49:41.298556 - Primary server down! Initiating failover...
2025-04-22 09:49:42.282059 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739AD50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:45.411479 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A2D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:47.292390 - Primary server down! Initiating failover...
2025-04-22 09:49:50.419864 - Primary server down! Initiating failover...
2025-04-22 09:49:51.385605 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739A420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:54.537168 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:49:56.398195 - Primary server down! Initiating failover...
2025-04-22 09:49:59.544565 - Primary server down! Initiating failover...
2025-04-22 09:50:00.489241 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:03.643350 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930BC80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:05.496477 - Primary server down! Initiating failover...
2025-04-22 09:50:08.649514 - Primary server down! Initiating failover...
2025-04-22 09:50:09.594838 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:12.733468 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8DCA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:14.606145 - Primary server down! Initiating failover...
2025-04-22 09:50:17.744320 - Primary server down! Initiating failover...
2025-04-22 09:50:18.683992 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:21.851896 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:23.691968 - Primary server down! Initiating failover...
2025-04-22 09:50:26.858898 - Primary server down! Initiating failover...
2025-04-22 09:50:27.766538 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739A780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:30.946537 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930BB90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:32.774179 - Primary server down! Initiating failover...
2025-04-22 09:50:35.953018 - Primary server down! Initiating failover...
2025-04-22 09:50:36.859508 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739AE40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:40.066522 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:41.866633 - Primary server down! Initiating failover...
2025-04-22 09:50:45.074767 - Primary server down! Initiating failover...
2025-04-22 09:50:45.962018 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B5C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:49.180416 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:50.968212 - Primary server down! Initiating failover...
2025-04-22 09:50:54.190461 - Primary server down! Initiating failover...
2025-04-22 09:50:55.070110 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:50:58.297534 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:00.076993 - Primary server down! Initiating failover...
2025-04-22 09:51:03.312070 - Primary server down! Initiating failover...
2025-04-22 09:51:04.167556 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB73989E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:07.430499 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:09.179899 - Primary server down! Initiating failover...
2025-04-22 09:51:12.443476 - Primary server down! Initiating failover...
2025-04-22 09:51:13.273664 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:16.550070 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8EF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:18.283674 - Primary server down! Initiating failover...
2025-04-22 09:51:21.564700 - Primary server down! Initiating failover...
2025-04-22 09:51:22.407630 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B7A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:25.697572 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:27.413797 - Primary server down! Initiating failover...
2025-04-22 09:51:30.711352 - Primary server down! Initiating failover...
2025-04-22 09:51:31.507211 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:34.817143 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A8A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:36.512039 - Primary server down! Initiating failover...
2025-04-22 09:51:39.822073 - Primary server down! Initiating failover...
2025-04-22 09:51:40.635549 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739A0C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:43.940573 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930AF30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:45.642751 - Primary server down! Initiating failover...
2025-04-22 09:51:48.954231 - Primary server down! Initiating failover...
2025-04-22 09:51:49.735609 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:53.054484 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:51:54.744015 - Primary server down! Initiating failover...
2025-04-22 09:51:58.061466 - Primary server down! Initiating failover...
2025-04-22 09:51:58.853006 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701FCE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:02.160474 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8E5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:03.860147 - Primary server down! Initiating failover...
2025-04-22 09:52:07.167351 - Primary server down! Initiating failover...
2025-04-22 09:52:07.964340 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB7399490>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:11.271286 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518F8F4A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:12.982846 - Primary server down! Initiating failover...
2025-04-22 09:52:16.285831 - Primary server down! Initiating failover...
2025-04-22 09:52:17.092373 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739AB10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:20.360654 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930BB60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:22.106382 - Primary server down! Initiating failover...
2025-04-22 09:52:25.373048 - Primary server down! Initiating failover...
2025-04-22 09:52:26.203493 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:29.473498 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:31.214380 - Primary server down! Initiating failover...
2025-04-22 09:52:34.487301 - Primary server down! Initiating failover...
2025-04-22 09:52:35.342455 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BA40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:38.589376 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:38.682918 - Primary server down! Initiating failover...
2025-04-22 09:52:40.352314 - Primary server down! Initiating failover...
2025-04-22 09:52:42.789728 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2267485C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:43.600811 - Primary server down! Initiating failover...
2025-04-22 09:52:44.481305 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB5CB9910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:47.702456 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:47.796567 - Primary server down! Initiating failover...
2025-04-22 09:52:49.493459 - Primary server down! Initiating failover...
2025-04-22 09:52:51.908177 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2268FD700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:52.713398 - Primary server down! Initiating failover...
2025-04-22 09:52:53.612919 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB701DB80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:56.813013 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518D48A10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:52:56.920771 - Primary server down! Initiating failover...
2025-04-22 09:52:58.619170 - Primary server down! Initiating failover...
2025-04-22 09:53:01.035686 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2266B8950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:01.822232 - Primary server down! Initiating failover...
2025-04-22 09:53:02.707906 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739BEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:05.925496 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519334D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:06.047432 - Primary server down! Initiating failover...
2025-04-22 09:53:07.719529 - Primary server down! Initiating failover...
2025-04-22 09:53:10.178333 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A2268FD640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:10.940103 - Primary server down! Initiating failover...
2025-04-22 09:53:11.824645 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000016BB739B1A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:15.063000 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:15.192576 - Primary server down! Initiating failover...
2025-04-22 09:53:16.831925 - Primary server down! Initiating failover...
2025-04-22 09:53:20.073251 - Primary server down! Initiating failover...
2025-04-22 09:53:24.174290 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:29.182157 - Primary server down! Initiating failover...
2025-04-22 09:53:33.269280 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:38.279818 - Primary server down! Initiating failover...
2025-04-22 09:53:42.368408 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:47.373195 - Primary server down! Initiating failover...
2025-04-22 09:53:51.486482 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025518EF17C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:53:56.498945 - Primary server down! Initiating failover...
2025-04-22 09:54:00.604252 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519335640>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:05.615718 - Primary server down! Initiating failover...
2025-04-22 09:54:09.697428 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B6E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:14.703524 - Primary server down! Initiating failover...
2025-04-22 09:54:18.822784 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930B920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:23.828689 - Primary server down! Initiating failover...
2025-04-22 09:54:27.926620 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002551930A780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:32.931974 - Primary server down! Initiating failover...
2025-04-22 09:54:37.026352 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:42.036376 - Primary server down! Initiating failover...
2025-04-22 09:54:46.132483 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519335700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:54:51.137490 - Primary server down! Initiating failover...
2025-04-22 09:54:55.263724 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519335F10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:55:00.276838 - Primary server down! Initiating failover...
2025-04-22 09:55:04.407247 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025519309C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 09:55:09.419600 - Primary server down! Initiating failover...
