2025-04-21 09:48:55.974431 - Primary server down! Initiating failover...
2025-04-21 09:49:00.080184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1907AA420>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:05.086077 - Primary server down! Initiating failover...
2025-04-21 09:49:09.186184 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:14.196321 - Primary server down! Initiating failover...
2025-04-21 09:49:18.278341 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:23.286987 - Primary server down! Initiating failover...
2025-04-21 09:49:27.361191 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4EC90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:32.370625 - Primary server down! Initiating failover...
2025-04-21 09:49:36.464439 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:41.474014 - Primary server down! Initiating failover...
2025-04-21 09:49:45.554772 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E4FE60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:50.566231 - Primary server down! Initiating failover...
2025-04-21 09:49:54.673839 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A193E806B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-21 09:49:59.684251 - Primary server down! Initiating failover...
2025-04-21 09:50:03.772106 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A1932B7D70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:28.137094 - Primary server down! Initiating failover...
2025-04-22 08:26:32.261129 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783800>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:37.272782 - Primary server down! Initiating failover...
2025-04-22 08:26:41.403676 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:46.418164 - Primary server down! Initiating failover...
2025-04-22 08:26:50.527435 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:26:55.540960 - Primary server down! Initiating failover...
2025-04-22 08:26:59.641942 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8656A8200>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:04.652351 - Primary server down! Initiating failover...
2025-04-22 08:27:08.791692 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B05C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:13.796568 - Primary server down! Initiating failover...
2025-04-22 08:27:17.906849 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:22.916250 - Primary server down! Initiating failover...
2025-04-22 08:27:27.045972 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B1520>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:32.057438 - Primary server down! Initiating failover...
2025-04-22 08:27:36.175937 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C864D25D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:41.189172 - Primary server down! Initiating failover...
2025-04-22 08:27:45.300037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:50.316991 - Primary server down! Initiating failover...
2025-04-22 08:27:54.424037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B11F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:27:59.432200 - Primary server down! Initiating failover...
2025-04-22 08:28:03.535293 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:08.540544 - Primary server down! Initiating failover...
2025-04-22 08:28:12.666074 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:17.674748 - Primary server down! Initiating failover...
2025-04-22 08:28:21.772275 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:26.783925 - Primary server down! Initiating failover...
2025-04-22 08:28:30.879967 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2E40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:35.892430 - Primary server down! Initiating failover...
2025-04-22 08:28:40.009438 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783FE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:45.016022 - Primary server down! Initiating failover...
2025-04-22 08:28:49.140819 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B24E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:28:54.153837 - Primary server down! Initiating failover...
2025-04-22 08:28:58.253703 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0140>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:03.259330 - Primary server down! Initiating failover...
2025-04-22 08:29:07.358527 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0B30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:12.370508 - Primary server down! Initiating failover...
2025-04-22 08:29:16.505378 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B12E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:21.519632 - Primary server down! Initiating failover...
2025-04-22 08:29:25.634458 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B1B20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:30.640325 - Primary server down! Initiating failover...
2025-04-22 08:29:34.729477 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:39.740989 - Primary server down! Initiating failover...
2025-04-22 08:29:43.868730 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:48.883130 - Primary server down! Initiating failover...
2025-04-22 08:29:53.013198 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B04D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:29:58.021100 - Primary server down! Initiating failover...
2025-04-22 08:30:02.132863 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:07.137336 - Primary server down! Initiating failover...
2025-04-22 08:30:11.252116 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:16.264930 - Primary server down! Initiating failover...
2025-04-22 08:30:20.400452 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:25.409077 - Primary server down! Initiating failover...
2025-04-22 08:30:29.510261 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783830>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:34.516393 - Primary server down! Initiating failover...
2025-04-22 08:30:38.621450 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B2330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:43.633531 - Primary server down! Initiating failover...
2025-04-22 08:30:47.752091 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:30:52.757667 - Primary server down! Initiating failover...
2025-04-22 08:30:56.842759 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:01.850707 - Primary server down! Initiating failover...
2025-04-22 08:31:05.964367 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:10.977721 - Primary server down! Initiating failover...
2025-04-22 08:31:15.090407 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B3710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:20.104328 - Primary server down! Initiating failover...
2025-04-22 08:31:24.223037 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C865783D10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:29.234241 - Primary server down! Initiating failover...
2025-04-22 08:31:33.339701 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:38.348958 - Primary server down! Initiating failover...
2025-04-22 08:31:42.441581 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0C20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:47.455495 - Primary server down! Initiating failover...
2025-04-22 08:31:51.565960 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B0B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2025-04-22 08:31:56.574810 - Primary server down! Initiating failover...
2025-04-22 08:32:00.657521 - Failed to trigger failover: HTTPConnectionPool(host='localhost', port=6000): Max retries exceeded with url: /failover (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8657B25D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
